services:
  mysql:
    image: mysql:latest 
    environment:
      MYSQL_ROOT_PASSWORD: rockCcLl$1_
      MYSQL_DATABASE: ENCUESTA  
      MYSQL_USER: lorelval 
      MYSQL_PASSWORD: rockCcLl$1_
    network_mode: host
    ports:
      - "3306:3306"  
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database_dump.sql:/docker-entrypoint-initdb.d/database_dump.sql
    command: --init-file /docker-entrypoint-initdb.d/database_dump.sql

  app:
    build: .
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
    ports:
      - "3000:3000"
    network_mode: host


volumes:
  mysql-data:
