version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ENCUESTA
    ports:
      - "3306:3306"
    volumes:
      - ./backups:/docker-entrypoint-initdb.d